-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  date date NOT NULL,
  check_in timestamp with time zone,
  check_out timestamp with time zone,
  break_start timestamp with time zone,
  break_end timestamp with time zone,
  status character varying DEFAULT 'present'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_manual boolean DEFAULT false,
  approval_status character varying DEFAULT 'approved'::character varying,
  request_notes text,
  approved_by uuid,
  approved_at timestamp with time zone,
  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT attendance_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.employees(id)
);
CREATE TABLE public.attendance_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code character varying NOT NULL UNIQUE,
  generated_by uuid,
  valid_for_date date NOT NULL,
  valid_from time without time zone NOT NULL,
  valid_until time without time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT attendance_codes_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_codes_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES public.employees(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  user_type character varying,
  action character varying NOT NULL,
  table_name character varying,
  record_id uuid,
  old_data jsonb,
  new_data jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contact_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  subject character varying,
  message text NOT NULL,
  status character varying DEFAULT 'unread'::character varying CHECK (status::text = ANY (ARRAY['unread'::character varying, 'read'::character varying, 'replied'::character varying, 'archived'::character varying]::text[])),
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  ip_address inet,
  user_agent text,
  reply_message text,
  replied_by uuid,
  replied_at timestamp with time zone,
  reply_sent_via character varying DEFAULT 'email'::character varying CHECK (reply_sent_via::text = ANY (ARRAY['email'::character varying, 'phone'::character varying, 'both'::character varying]::text[])),
  customer_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_messages_pkey PRIMARY KEY (id),
  CONSTRAINT contact_messages_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT contact_messages_replied_by_fkey FOREIGN KEY (replied_by) REFERENCES public.employees(id)
);
CREATE TABLE public.customer_invoice_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  invoice_number text NOT NULL,
  order_id uuid,
  order_type text,
  items jsonb,
  subtotal numeric,
  discount numeric DEFAULT 0,
  tax numeric DEFAULT 0,
  total numeric NOT NULL,
  payment_method text,
  payment_status text,
  promo_code_used text,
  loyalty_points_used integer DEFAULT 0,
  loyalty_points_earned integer DEFAULT 0,
  billed_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT customer_invoice_records_pkey PRIMARY KEY (id),
  CONSTRAINT customer_invoice_records_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_invoice_records_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT customer_invoice_records_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.customer_promo_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  customer_id uuid NOT NULL,
  promo_code_id uuid,
  code text NOT NULL UNIQUE,
  promo_type text NOT NULL CHECK (promo_type = ANY (ARRAY['percentage'::text, 'fixed_amount'::text])),
  value numeric NOT NULL,
  max_discount numeric,
  name text NOT NULL,
  description text,
  loyalty_points_required integer NOT NULL,
  is_used boolean DEFAULT false,
  used_at timestamp with time zone,
  used_on_order_id uuid,
  expires_at timestamp with time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT customer_promo_codes_pkey PRIMARY KEY (id),
  CONSTRAINT customer_promo_codes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT customer_promo_codes_promo_code_id_fkey FOREIGN KEY (promo_code_id) REFERENCES public.promo_codes(id),
  CONSTRAINT customer_promo_codes_used_on_order_id_fkey FOREIGN KEY (used_on_order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.customers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  auth_user_id uuid UNIQUE,
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  phone character varying UNIQUE,
  address text,
  is_verified boolean DEFAULT false,
  is_2fa_enabled boolean DEFAULT false,
  two_fa_secret text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  favorites jsonb DEFAULT '[]'::jsonb,
  is_banned boolean DEFAULT false,
  ban_reason text,
  banned_at timestamp with time zone,
  banned_by uuid,
  unbanned_at timestamp with time zone,
  unbanned_by uuid,
  notification_preferences jsonb DEFAULT '{"order_updates": true, "new_menu_items": false, "loyalty_rewards": true, "sms_notifications": false, "promotional_offers": true, "push_notifications": false, "email_notifications": true}'::jsonb,
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT customers_banned_by_fkey FOREIGN KEY (banned_by) REFERENCES public.employees(id),
  CONSTRAINT customers_unbanned_by_fkey FOREIGN KEY (unbanned_by) REFERENCES public.employees(id)
);
CREATE TABLE public.deal_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  deal_id uuid NOT NULL,
  menu_item_id uuid NOT NULL,
  quantity integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT deal_items_pkey PRIMARY KEY (id),
  CONSTRAINT deal_items_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT deal_items_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.deals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  discount_percentage numeric,
  discount_amount numeric,
  images jsonb DEFAULT '[]'::jsonb,
  applicable_items jsonb,
  minimum_order_amount numeric,
  is_active boolean DEFAULT true,
  valid_from timestamp with time zone,
  valid_until timestamp with time zone,
  usage_limit integer,
  usage_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  code character varying UNIQUE,
  deal_type character varying DEFAULT 'combo'::character varying,
  original_price numeric DEFAULT 0,
  discounted_price numeric DEFAULT 0,
  image_url text,
  is_featured boolean DEFAULT false,
  CONSTRAINT deals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.delivery_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rider_id uuid NOT NULL,
  order_id uuid NOT NULL,
  order_number text NOT NULL,
  order_snapshot jsonb NOT NULL,
  customer_name text NOT NULL,
  customer_phone text,
  customer_address text,
  customer_email text,
  items jsonb NOT NULL,
  total_items integer NOT NULL DEFAULT 0,
  subtotal numeric NOT NULL DEFAULT 0,
  delivery_fee numeric DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  payment_method text,
  payment_status text,
  accepted_at timestamp with time zone NOT NULL DEFAULT now(),
  started_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  delivery_status text NOT NULL DEFAULT 'accepted'::text CHECK (delivery_status = ANY (ARRAY['accepted'::text, 'delivering'::text, 'delivered'::text, 'cancelled'::text, 'returned'::text])),
  estimated_delivery_minutes integer,
  actual_delivery_minutes integer,
  distance_km numeric,
  delivery_notes text,
  customer_rating integer CHECK (customer_rating >= 1 AND customer_rating <= 5),
  customer_feedback text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT delivery_history_pkey PRIMARY KEY (id),
  CONSTRAINT delivery_history_rider_id_fkey FOREIGN KEY (rider_id) REFERENCES public.employees(id),
  CONSTRAINT delivery_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.employee_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  document_type character varying NOT NULL,
  document_name character varying NOT NULL,
  file_url text NOT NULL,
  file_type character varying,
  uploaded_at timestamp with time zone DEFAULT now(),
  verified boolean DEFAULT false,
  verified_by uuid,
  verified_at timestamp with time zone,
  CONSTRAINT employee_documents_pkey PRIMARY KEY (id),
  CONSTRAINT employee_documents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_documents_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_licenses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  license_id character varying NOT NULL UNIQUE,
  issued_at timestamp with time zone DEFAULT now(),
  activated_at timestamp with time zone,
  activation_ip inet,
  is_used boolean DEFAULT false,
  expires_at timestamp with time zone,
  CONSTRAINT employee_licenses_pkey PRIMARY KEY (id),
  CONSTRAINT employee_licenses_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.employee_payroll (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid,
  month integer NOT NULL,
  year integer NOT NULL,
  base_salary numeric NOT NULL,
  bonus numeric DEFAULT 0,
  deductions numeric DEFAULT 0,
  tips numeric DEFAULT 0,
  total_amount numeric NOT NULL,
  paid boolean DEFAULT false,
  paid_at timestamp with time zone,
  paid_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  payment_frequency text DEFAULT 'monthly'::text CHECK (payment_frequency = ANY (ARRAY['daily'::text, 'weekly'::text, 'biweekly'::text, 'monthly'::text, 'quarterly'::text, 'yearly'::text])),
  bank_details jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT employee_payroll_pkey PRIMARY KEY (id),
  CONSTRAINT employee_payroll_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT employee_payroll_paid_by_fkey FOREIGN KEY (paid_by) REFERENCES public.employees(id)
);
CREATE TABLE public.employees (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  auth_user_id uuid UNIQUE,
  employee_id character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  email character varying NOT NULL UNIQUE,
  phone character varying NOT NULL UNIQUE,
  role USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::employee_status,
  permissions jsonb DEFAULT '{}'::jsonb,
  documents jsonb DEFAULT '[]'::jsonb,
  salary numeric,
  hired_date date,
  created_by uuid,
  is_2fa_enabled boolean DEFAULT false,
  two_fa_secret text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  license_id character varying UNIQUE,
  avatar_url text,
  address text,
  emergency_contact character varying,
  emergency_contact_name character varying,
  date_of_birth date,
  blood_group character varying,
  portal_enabled boolean DEFAULT false,
  last_login timestamp with time zone,
  total_tips numeric DEFAULT 0,
  total_orders_taken integer DEFAULT 0,
  bank_details jsonb DEFAULT '{}'::jsonb,
  notes text,
  block_reason text,
  CONSTRAINT employees_pkey PRIMARY KEY (id),
  CONSTRAINT employees_auth_user_id_fkey FOREIGN KEY (auth_user_id) REFERENCES auth.users(id),
  CONSTRAINT employees_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  category character varying NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  unit character varying NOT NULL,
  min_quantity numeric NOT NULL DEFAULT 0,
  cost_per_unit numeric NOT NULL DEFAULT 0,
  supplier character varying,
  last_restocked timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  sku character varying,
  max_quantity numeric DEFAULT 100,
  notes text,
  created_by uuid,
  location character varying,
  barcode character varying,
  expiry_date date,
  is_active boolean DEFAULT true,
  reorder_point numeric DEFAULT 10,
  lead_time_days integer DEFAULT 7,
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id)
);
CREATE TABLE public.inventory_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inventory_id uuid,
  alert_type character varying NOT NULL CHECK (alert_type::text = ANY (ARRAY['low_stock'::character varying, 'out_of_stock'::character varying, 'expiring'::character varying, 'expired'::character varying, 'overstock'::character varying]::text[])),
  message text NOT NULL,
  is_read boolean DEFAULT false,
  is_resolved boolean DEFAULT false,
  resolved_by uuid,
  resolved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_alerts_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id),
  CONSTRAINT inventory_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.employees(id)
);
CREATE TABLE public.inventory_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  description text,
  parent_id uuid,
  color character varying,
  icon character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_categories_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.inventory_categories(id)
);
CREATE TABLE public.inventory_purchase_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  po_number character varying NOT NULL UNIQUE,
  supplier_id uuid,
  supplier_name character varying,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'pending'::character varying, 'approved'::character varying, 'ordered'::character varying, 'partial'::character varying, 'received'::character varying, 'cancelled'::character varying]::text[])),
  items jsonb NOT NULL DEFAULT '[]'::jsonb,
  subtotal numeric DEFAULT 0,
  tax numeric DEFAULT 0,
  shipping numeric DEFAULT 0,
  total numeric DEFAULT 0,
  expected_date date,
  received_date date,
  notes text,
  created_by uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_purchase_orders_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES public.inventory_suppliers(id),
  CONSTRAINT inventory_purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id),
  CONSTRAINT inventory_purchase_orders_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.employees(id)
);
CREATE TABLE public.inventory_suppliers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  contact_person character varying,
  email character varying,
  phone character varying,
  address text,
  city character varying,
  payment_terms character varying,
  lead_time_days integer DEFAULT 7,
  rating numeric,
  is_active boolean DEFAULT true,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_suppliers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  inventory_id uuid NOT NULL,
  type character varying NOT NULL,
  quantity numeric NOT NULL,
  previous_quantity numeric NOT NULL,
  new_quantity numeric NOT NULL,
  reason text,
  performed_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  transaction_type character varying,
  quantity_change numeric,
  unit_cost numeric,
  total_cost numeric,
  notes text,
  created_by uuid,
  reference_number character varying,
  batch_number character varying,
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transactions_inventory_id_fkey FOREIGN KEY (inventory_id) REFERENCES public.inventory(id),
  CONSTRAINT inventory_transactions_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.employees(id),
  CONSTRAINT inventory_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id)
);
CREATE TABLE public.invoices (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  invoice_number character varying NOT NULL UNIQUE,
  order_id uuid,
  customer_id uuid,
  customer_name character varying NOT NULL,
  customer_phone character varying,
  customer_email character varying,
  order_type character varying NOT NULL,
  items jsonb NOT NULL,
  subtotal numeric NOT NULL,
  discount numeric DEFAULT 0,
  discount_details jsonb,
  tax numeric DEFAULT 0,
  delivery_fee numeric DEFAULT 0,
  service_charge numeric DEFAULT 0,
  tip numeric DEFAULT 0,
  total numeric NOT NULL,
  payment_method character varying,
  payment_status USER-DEFINED DEFAULT 'pending'::invoice_status,
  loyalty_points_earned integer DEFAULT 0,
  table_number integer,
  served_by uuid,
  billed_by uuid,
  printed boolean DEFAULT false,
  printed_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  bill_status text DEFAULT 'pending'::text CHECK (bill_status = ANY (ARRAY['pending'::text, 'generated'::text, 'paid'::text, 'void'::text, 'refunded'::text])),
  promo_code_id uuid,
  promo_code_value text,
  void_reason text,
  voided_by uuid,
  voided_at timestamp with time zone,
  table_session_id uuid,
  brand_info jsonb DEFAULT '{"ntn": "XXXXXXX", "name": "ZOIRO Broast", "email": "info@zoiro.com", "phone": "+92 XXX XXXXXXX", "address": "Main Branch, City", "tagline": "Injected Broast - Saucy. Juicy. Crispy.", "logo_url": "/assets/logo.png"}'::jsonb,
  loyalty_points_used integer DEFAULT 0,
  CONSTRAINT invoices_pkey PRIMARY KEY (id),
  CONSTRAINT invoices_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT invoices_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT invoices_served_by_fkey FOREIGN KEY (served_by) REFERENCES public.employees(id),
  CONSTRAINT invoices_billed_by_fkey FOREIGN KEY (billed_by) REFERENCES public.employees(id),
  CONSTRAINT invoices_promo_code_id_fkey FOREIGN KEY (promo_code_id) REFERENCES public.promo_codes(id),
  CONSTRAINT invoices_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES public.employees(id)
);
CREATE TABLE public.leave_balances (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL UNIQUE,
  annual_leave integer DEFAULT 14,
  sick_leave integer DEFAULT 10,
  casual_leave integer DEFAULT 5,
  annual_used integer DEFAULT 0,
  sick_used integer DEFAULT 0,
  casual_used integer DEFAULT 0,
  year integer DEFAULT (EXTRACT(year FROM CURRENT_DATE))::integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leave_balances_pkey PRIMARY KEY (id),
  CONSTRAINT leave_balances_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id)
);
CREATE TABLE public.leave_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  leave_type character varying NOT NULL CHECK (leave_type::text = ANY (ARRAY['annual'::character varying, 'sick'::character varying, 'casual'::character varying, 'emergency'::character varying, 'unpaid'::character varying, 'maternity'::character varying, 'paternity'::character varying, 'other'::character varying]::text[])),
  start_date date NOT NULL,
  end_date date NOT NULL,
  total_days integer NOT NULL,
  reason text NOT NULL,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'cancelled'::character varying]::text[])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leave_requests_pkey PRIMARY KEY (id),
  CONSTRAINT leave_requests_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT leave_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.employees(id)
);
CREATE TABLE public.loyalty_points (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid,
  order_id uuid,
  points integer NOT NULL,
  type character varying NOT NULL CHECK (type::text = ANY (ARRAY['earned'::character varying, 'redeemed'::character varying, 'bonus'::character varying, 'expired'::character varying]::text[])),
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_points_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_points_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT loyalty_points_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.loyalty_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid,
  points_change integer NOT NULL,
  transaction_type character varying NOT NULL,
  order_id uuid,
  description text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT loyalty_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT loyalty_transactions_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT loyalty_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT loyalty_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id)
);
CREATE TABLE public.maintenance_mode (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  is_enabled boolean NOT NULL DEFAULT false,
  reason_type text NOT NULL DEFAULT 'update'::text CHECK (reason_type = ANY (ARRAY['update'::text, 'bug_fix'::text, 'changes'::text, 'scheduled'::text, 'custom'::text])),
  custom_reason text,
  title text DEFAULT 'We''ll Be Right Back'::text,
  message text DEFAULT 'Our website is currently undergoing scheduled maintenance. We apologize for any inconvenience.'::text,
  estimated_restore_time timestamp with time zone,
  show_timer boolean DEFAULT true,
  show_progress boolean DEFAULT true,
  enabled_at timestamp with time zone,
  enabled_by uuid,
  email_sent_at timestamp with time zone,
  email_sent_count integer DEFAULT 0,
  last_check timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT maintenance_mode_pkey PRIMARY KEY (id),
  CONSTRAINT maintenance_mode_enabled_by_fkey FOREIGN KEY (enabled_by) REFERENCES public.employees(id)
);
CREATE TABLE public.meals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  price numeric NOT NULL,
  original_price numeric,
  images jsonb DEFAULT '[]'::jsonb,
  items jsonb NOT NULL,
  is_available boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  valid_from timestamp with time zone,
  valid_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  rating numeric DEFAULT 0,
  total_reviews integer DEFAULT 0,
  CONSTRAINT meals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.menu_categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  image_url text,
  display_order integer DEFAULT 0,
  is_visible boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT menu_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.menu_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  category_id uuid,
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  price numeric NOT NULL,
  images jsonb DEFAULT '[]'::jsonb,
  is_available boolean DEFAULT true,
  is_featured boolean DEFAULT false,
  preparation_time integer,
  rating numeric DEFAULT 0,
  total_reviews integer DEFAULT 0,
  tags jsonb DEFAULT '[]'::jsonb,
  nutritional_info jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  size_variants jsonb,
  has_variants boolean DEFAULT false,
  piece_count integer,
  serves_count integer,
  includes text,
  image_url text,
  CONSTRAINT menu_items_pkey PRIMARY KEY (id),
  CONSTRAINT menu_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.menu_categories(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  user_type character varying NOT NULL,
  title character varying NOT NULL,
  message text NOT NULL,
  type character varying,
  is_read boolean DEFAULT false,
  data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  priority character varying DEFAULT 'normal'::character varying,
  action_url text,
  expires_at timestamp with time zone,
  sent_by uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.order_activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL,
  action text NOT NULL,
  action_by uuid,
  action_by_name text,
  details jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT order_activity_log_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_activity_log_action_by_fkey FOREIGN KEY (action_by) REFERENCES public.employees(id)
);
CREATE TABLE public.order_cancellations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid,
  cancelled_by uuid,
  reason text,
  refund_amount numeric,
  refund_status character varying DEFAULT 'pending'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_cancellations_pkey PRIMARY KEY (id),
  CONSTRAINT order_cancellations_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_cancellations_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.employees(id)
);
CREATE TABLE public.order_status_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid,
  status USER-DEFINED NOT NULL,
  changed_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT order_status_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_number character varying NOT NULL UNIQUE,
  customer_id uuid,
  customer_name character varying NOT NULL,
  customer_email character varying,
  customer_phone character varying NOT NULL,
  customer_address text,
  order_type USER-DEFINED DEFAULT 'online'::order_type,
  items jsonb NOT NULL,
  subtotal numeric NOT NULL,
  discount numeric DEFAULT 0,
  delivery_fee numeric DEFAULT 0,
  tax numeric DEFAULT 0,
  total numeric NOT NULL,
  payment_method USER-DEFINED NOT NULL,
  payment_status character varying DEFAULT 'pending'::character varying,
  status USER-DEFINED DEFAULT 'pending'::order_status,
  notes text,
  table_number integer,
  assigned_to uuid,
  prepared_by uuid,
  delivered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  payment_proof_url text,
  waiter_id uuid,
  kitchen_started_at timestamp with time zone,
  kitchen_completed_at timestamp with time zone,
  can_cancel_until timestamp with time zone,
  cancellation_reason text,
  delivery_rider_id uuid,
  delivery_started_at timestamp with time zone,
  estimated_delivery_time timestamp with time zone,
  customer_notified boolean DEFAULT false,
  transaction_id text,
  online_payment_method_id uuid,
  online_payment_details jsonb,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT orders_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.employees(id),
  CONSTRAINT orders_prepared_by_fkey FOREIGN KEY (prepared_by) REFERENCES public.employees(id),
  CONSTRAINT orders_waiter_id_fkey FOREIGN KEY (waiter_id) REFERENCES public.employees(id),
  CONSTRAINT orders_delivery_rider_id_fkey FOREIGN KEY (delivery_rider_id) REFERENCES public.employees(id),
  CONSTRAINT fk_orders_payment_method FOREIGN KEY (online_payment_method_id) REFERENCES public.payment_methods(id)
);
CREATE TABLE public.otp_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL,
  code character varying NOT NULL,
  purpose character varying NOT NULL,
  is_used boolean DEFAULT false,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT otp_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.password_reset_otps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL,
  otp_hash character varying NOT NULL,
  purpose character varying DEFAULT 'password_reset'::character varying,
  expires_at timestamp with time zone NOT NULL,
  attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  is_verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT password_reset_otps_pkey PRIMARY KEY (id)
);
CREATE TABLE public.password_reset_rate_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email character varying NOT NULL UNIQUE,
  attempt_count integer DEFAULT 1,
  first_attempt_at timestamp with time zone DEFAULT now(),
  last_attempt_at timestamp with time zone DEFAULT now(),
  cooldown_until timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT password_reset_rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_methods (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  method_type text NOT NULL CHECK (method_type = ANY (ARRAY['jazzcash'::text, 'easypaisa'::text, 'bank'::text])),
  method_name text NOT NULL,
  account_number text NOT NULL,
  account_holder_name text NOT NULL,
  bank_name text,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_methods_pkey PRIMARY KEY (id)
);
CREATE TABLE public.payment_records (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  customer_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_method USER-DEFINED NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  proof_url text,
  transaction_id text,
  verified_by uuid,
  verified_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_records_pkey PRIMARY KEY (id),
  CONSTRAINT payment_records_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT payment_records_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT payment_records_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.employees(id)
);
CREATE TABLE public.payslips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  employee_id uuid NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  base_salary numeric NOT NULL,
  overtime_hours numeric DEFAULT 0,
  overtime_rate numeric DEFAULT 1.5,
  bonuses numeric DEFAULT 0,
  deductions numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  net_salary numeric NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  payment_method character varying,
  paid_at timestamp with time zone,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payslips_pkey PRIMARY KEY (id),
  CONSTRAINT payslips_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.employees(id),
  CONSTRAINT payslips_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id)
);
CREATE TABLE public.perks_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key text NOT NULL UNIQUE,
  setting_value jsonb NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT perks_settings_pkey PRIMARY KEY (id),
  CONSTRAINT perks_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.employees(id)
);
CREATE TABLE public.promo_code_usage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid NOT NULL,
  deal_id uuid NOT NULL,
  order_id uuid NOT NULL,
  discount_applied numeric NOT NULL,
  used_at timestamp with time zone DEFAULT now(),
  CONSTRAINT promo_code_usage_pkey PRIMARY KEY (id),
  CONSTRAINT promo_code_usage_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT promo_code_usage_deal_id_fkey FOREIGN KEY (deal_id) REFERENCES public.deals(id),
  CONSTRAINT promo_code_usage_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.promo_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  promo_type USER-DEFINED NOT NULL,
  value numeric NOT NULL,
  min_order_amount numeric DEFAULT 0,
  max_discount numeric,
  usage_limit integer,
  usage_per_customer integer DEFAULT 1,
  current_usage integer DEFAULT 0,
  applicable_items jsonb,
  valid_from timestamp with time zone NOT NULL,
  valid_until timestamp with time zone NOT NULL,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  customer_id uuid,
  loyalty_points_required integer,
  CONSTRAINT promo_codes_pkey PRIMARY KEY (id),
  CONSTRAINT promo_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id),
  CONSTRAINT promo_codes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.push_notification_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  target_user_ids ARRAY DEFAULT '{}'::uuid[],
  target_user_type character varying DEFAULT 'all'::character varying CHECK (target_user_type::text = ANY (ARRAY['employee'::character varying, 'customer'::character varying, 'all'::character varying]::text[])),
  target_roles ARRAY DEFAULT '{}'::text[],
  title text NOT NULL,
  body text NOT NULL,
  icon text DEFAULT '/assets/zoiro-logo.png'::text,
  badge text DEFAULT '/assets/zoiro-badge.png'::text,
  image text,
  tag character varying,
  notification_type character varying NOT NULL,
  reference_id uuid,
  data jsonb DEFAULT '{}'::jsonb,
  priority character varying DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'normal'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'processing'::character varying, 'sent'::character varying, 'failed'::character varying, 'partial'::character varying]::text[])),
  sent_count integer DEFAULT 0,
  failed_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  error_details jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  CONSTRAINT push_notification_queue_pkey PRIMARY KEY (id)
);
CREATE TABLE public.push_subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  user_type character varying NOT NULL CHECK (user_type::text = ANY (ARRAY['employee'::character varying, 'customer'::character varying]::text[])),
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  is_active boolean DEFAULT true,
  device_info jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_used_at timestamp with time zone DEFAULT now(),
  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.push_tokens (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  user_type character varying NOT NULL,
  token text NOT NULL,
  device_type character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT push_tokens_pkey PRIMARY KEY (id)
);
CREATE TABLE public.reports_archive (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  report_type character varying NOT NULL,
  report_period character varying,
  start_date date NOT NULL,
  end_date date NOT NULL,
  data jsonb NOT NULL,
  file_url text,
  generated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reports_archive_pkey PRIMARY KEY (id),
  CONSTRAINT reports_archive_generated_by_fkey FOREIGN KEY (generated_by) REFERENCES public.employees(id)
);
CREATE TABLE public.restaurant_tables (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  table_number integer NOT NULL UNIQUE,
  capacity integer NOT NULL,
  status USER-DEFINED DEFAULT 'available'::table_status,
  section character varying,
  floor integer DEFAULT 1,
  position jsonb,
  current_order_id uuid,
  current_customers integer DEFAULT 0,
  assigned_waiter_id uuid,
  reserved_by uuid,
  reservation_time timestamp with time zone,
  reservation_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT restaurant_tables_pkey PRIMARY KEY (id),
  CONSTRAINT restaurant_tables_assigned_waiter_id_fkey FOREIGN KEY (assigned_waiter_id) REFERENCES public.employees(id),
  CONSTRAINT restaurant_tables_reserved_by_fkey FOREIGN KEY (reserved_by) REFERENCES public.customers(id)
);
CREATE TABLE public.review_helpful_votes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  review_id uuid NOT NULL,
  customer_id uuid,
  ip_address character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT review_helpful_votes_pkey PRIMARY KEY (id),
  CONSTRAINT review_helpful_votes_review_id_fkey FOREIGN KEY (review_id) REFERENCES public.reviews(id),
  CONSTRAINT review_helpful_votes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.reviews (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  customer_id uuid,
  order_id uuid,
  item_id uuid,
  meal_id uuid,
  rating integer CHECK (rating >= 1 AND rating <= 5),
  comment text,
  images jsonb DEFAULT '[]'::jsonb,
  is_verified boolean DEFAULT false,
  is_visible boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  admin_reply text,
  replied_at timestamp with time zone,
  review_type character varying DEFAULT 'overall'::character varying,
  helpful_count integer DEFAULT 0,
  replied_by uuid,
  CONSTRAINT reviews_pkey PRIMARY KEY (id),
  CONSTRAINT reviews_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id),
  CONSTRAINT reviews_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT reviews_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.menu_items(id),
  CONSTRAINT reviews_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(id),
  CONSTRAINT reviews_replied_by_fkey FOREIGN KEY (replied_by) REFERENCES public.employees(id)
);
CREATE TABLE public.site_content (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  page character varying NOT NULL,
  section character varying NOT NULL,
  content jsonb NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT site_content_pkey PRIMARY KEY (id)
);
CREATE TABLE public.special_offer_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  offer_id uuid NOT NULL,
  menu_item_id uuid NOT NULL,
  original_price numeric NOT NULL,
  offer_price numeric NOT NULL,
  discount_percentage numeric,
  max_quantity_per_order integer,
  total_available_quantity integer,
  quantity_sold integer DEFAULT 0,
  size_variant character varying,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT special_offer_items_pkey PRIMARY KEY (id),
  CONSTRAINT special_offer_items_offer_id_fkey FOREIGN KEY (offer_id) REFERENCES public.special_offers(id),
  CONSTRAINT special_offer_items_menu_item_id_fkey FOREIGN KEY (menu_item_id) REFERENCES public.menu_items(id)
);
CREATE TABLE public.special_offers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  event_type character varying,
  banner_image text,
  popup_image text,
  thumbnail_image text,
  background_color character varying,
  theme_colors jsonb DEFAULT '{}'::jsonb,
  pakistani_flags boolean DEFAULT false,
  confetti_enabled boolean DEFAULT true,
  custom_css text,
  discount_type USER-DEFINED NOT NULL DEFAULT 'percentage'::offer_discount_type,
  discount_value numeric NOT NULL DEFAULT 0,
  min_order_amount numeric DEFAULT 0,
  max_discount_amount numeric,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  show_popup boolean DEFAULT true,
  popup_auto_close_seconds integer DEFAULT 5,
  status USER-DEFINED DEFAULT 'draft'::offer_status,
  is_visible boolean DEFAULT true,
  show_on_landing boolean DEFAULT true,
  show_in_menu boolean DEFAULT true,
  priority integer DEFAULT 0,
  notify_via_email boolean DEFAULT false,
  notify_via_push boolean DEFAULT false,
  notification_sent_at timestamp with time zone,
  notification_scheduled_at timestamp with time zone,
  auto_notify_on_start boolean DEFAULT false,
  view_count integer DEFAULT 0,
  click_count integer DEFAULT 0,
  conversion_count integer DEFAULT 0,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT special_offers_pkey PRIMARY KEY (id),
  CONSTRAINT special_offers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.employees(id),
  CONSTRAINT special_offers_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.employees(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  key text NOT NULL UNIQUE,
  value jsonb NOT NULL DEFAULT '{}'::jsonb,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.table_exchange_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  from_waiter_id uuid NOT NULL,
  to_waiter_id uuid NOT NULL,
  table_id uuid NOT NULL,
  exchange_type character varying NOT NULL,
  swap_table_id uuid,
  status character varying DEFAULT 'pending'::character varying,
  reason text,
  responded_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT table_exchange_requests_pkey PRIMARY KEY (id),
  CONSTRAINT table_exchange_requests_from_waiter_id_fkey FOREIGN KEY (from_waiter_id) REFERENCES public.employees(id),
  CONSTRAINT table_exchange_requests_to_waiter_id_fkey FOREIGN KEY (to_waiter_id) REFERENCES public.employees(id),
  CONSTRAINT table_exchange_requests_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.restaurant_tables(id),
  CONSTRAINT table_exchange_requests_swap_table_id_fkey FOREIGN KEY (swap_table_id) REFERENCES public.restaurant_tables(id)
);
CREATE TABLE public.table_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  table_id uuid,
  order_id uuid,
  waiter_id uuid,
  customer_count integer,
  opened_at timestamp with time zone NOT NULL,
  closed_at timestamp with time zone,
  total_bill numeric,
  tip_amount numeric DEFAULT 0,
  notes text,
  CONSTRAINT table_history_pkey PRIMARY KEY (id),
  CONSTRAINT table_history_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.restaurant_tables(id),
  CONSTRAINT table_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT table_history_waiter_id_fkey FOREIGN KEY (waiter_id) REFERENCES public.employees(id)
);
CREATE TABLE public.table_reservations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  table_id uuid NOT NULL,
  customer_id uuid,
  customer_name text NOT NULL,
  customer_phone text NOT NULL,
  customer_email text,
  reservation_date date NOT NULL,
  arrival_time time without time zone NOT NULL,
  party_size integer NOT NULL DEFAULT 1,
  pre_order_items jsonb NOT NULL DEFAULT '[]'::jsonb,
  notes text,
  status text NOT NULL DEFAULT 'confirmed'::text CHECK (status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'arrived'::text, 'cancelled'::text, 'expired'::text])),
  auto_release_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT table_reservations_pkey PRIMARY KEY (id),
  CONSTRAINT table_reservations_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.restaurant_tables(id),
  CONSTRAINT table_reservations_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.two_fa_setup (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  user_type character varying NOT NULL,
  secret text NOT NULL,
  backup_codes jsonb DEFAULT '[]'::jsonb,
  is_enabled boolean DEFAULT false,
  enabled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT two_fa_setup_pkey PRIMARY KEY (id)
);
CREATE TABLE public.waiter_order_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  waiter_id uuid NOT NULL,
  order_id uuid NOT NULL,
  order_number text NOT NULL,
  table_id uuid,
  table_number integer,
  customer_id uuid,
  customer_name text,
  customer_phone text,
  customer_email text,
  customer_count integer DEFAULT 1,
  is_registered_customer boolean DEFAULT false,
  items jsonb NOT NULL,
  total_items integer DEFAULT 0,
  subtotal numeric DEFAULT 0,
  discount numeric DEFAULT 0,
  tax numeric DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  payment_method text,
  payment_status text DEFAULT 'pending'::text,
  tip_amount numeric DEFAULT 0,
  invoice_number text,
  order_taken_at timestamp with time zone NOT NULL DEFAULT now(),
  order_confirmed_at timestamp with time zone,
  order_completed_at timestamp with time zone,
  order_status text DEFAULT 'pending'::text,
  confirmation_email_sent boolean DEFAULT false,
  confirmation_email_sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT waiter_order_history_pkey PRIMARY KEY (id),
  CONSTRAINT waiter_order_history_waiter_id_fkey FOREIGN KEY (waiter_id) REFERENCES public.employees(id),
  CONSTRAINT waiter_order_history_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT waiter_order_history_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.restaurant_tables(id),
  CONSTRAINT waiter_order_history_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);
CREATE TABLE public.waiter_tips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  waiter_id uuid,
  order_id uuid,
  invoice_id uuid,
  tip_amount numeric NOT NULL,
  table_id uuid,
  date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT waiter_tips_pkey PRIMARY KEY (id),
  CONSTRAINT waiter_tips_waiter_id_fkey FOREIGN KEY (waiter_id) REFERENCES public.employees(id),
  CONSTRAINT waiter_tips_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT waiter_tips_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.invoices(id),
  CONSTRAINT waiter_tips_table_id_fkey FOREIGN KEY (table_id) REFERENCES public.restaurant_tables(id)
);
CREATE TABLE public.website_content (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  key character varying NOT NULL UNIQUE,
  title character varying,
  content jsonb NOT NULL,
  section character varying,
  is_active boolean DEFAULT true,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT website_content_pkey PRIMARY KEY (id),
  CONSTRAINT website_content_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.employees(id)
);